# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiMain.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(451, 351)
        main.setMinimumSize(QtCore.QSize(451, 351))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/icons/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main.setWindowIcon(icon)
        main.setStyleSheet("QFrame#banner {background: qlineargradient(x1:0 y1:0, x2:0 y2:1, stop:0 #75818f, stop:1 #424953); border-radius: 0px;}\n"
"QLabel#titleLbl {color: white;}\n"
"QLabel#verLbl {color: white;}")
        self.centralwidget = QtWidgets.QWidget(main)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.banner = QtWidgets.QFrame(self.centralwidget)
        self.banner.setMinimumSize(QtCore.QSize(0, 81))
        self.banner.setMaximumSize(QtCore.QSize(16777215, 81))
        self.banner.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.banner.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.banner.setFrameShadow(QtWidgets.QFrame.Raised)
        self.banner.setLineWidth(0)
        self.banner.setObjectName("banner")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.banner)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(11, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.logoLbl = QtWidgets.QLabel(self.banner)
        self.logoLbl.setMinimumSize(QtCore.QSize(61, 61))
        self.logoLbl.setMaximumSize(QtCore.QSize(61, 61))
        self.logoLbl.setText("")
        self.logoLbl.setPixmap(QtGui.QPixmap(":/res/icons/main.png"))
        self.logoLbl.setScaledContents(True)
        self.logoLbl.setObjectName("logoLbl")
        self.horizontalLayout.addWidget(self.logoLbl)
        spacerItem1 = QtWidgets.QSpacerItem(11, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.titleFrm = QtWidgets.QFrame(self.banner)
        self.titleFrm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titleFrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleFrm.setLineWidth(0)
        self.titleFrm.setObjectName("titleFrm")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.titleFrm)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.titleLbl = QtWidgets.QLabel(self.titleFrm)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.titleLbl.setFont(font)
        self.titleLbl.setObjectName("titleLbl")
        self.verticalLayout_2.addWidget(self.titleLbl)
        self.verLbl = QtWidgets.QLabel(self.titleFrm)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.verLbl.setFont(font)
        self.verLbl.setObjectName("verLbl")
        self.verticalLayout_2.addWidget(self.verLbl)
        spacerItem3 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.titleFrm)
        self.verticalLayout.addWidget(self.banner)
        self.contentFrm = QtWidgets.QFrame(self.centralwidget)
        self.contentFrm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentFrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentFrm.setLineWidth(0)
        self.contentFrm.setObjectName("contentFrm")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.contentFrm)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dropLbl = QtWidgets.QLabel(self.contentFrm)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.dropLbl.setFont(font)
        self.dropLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.dropLbl.setObjectName("dropLbl")
        self.verticalLayout_3.addWidget(self.dropLbl)
        self.fixCbox = QtWidgets.QCheckBox(self.contentFrm)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.fixCbox.setFont(font)
        self.fixCbox.setChecked(True)
        self.fixCbox.setObjectName("fixCbox")
        self.verticalLayout_3.addWidget(self.fixCbox)
        self.verticalLayout.addWidget(self.contentFrm)
        self.statusFrm = QtWidgets.QFrame(self.centralwidget)
        self.statusFrm.setMinimumSize(QtCore.QSize(0, 31))
        self.statusFrm.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.statusFrm.setFont(font)
        self.statusFrm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.statusFrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statusFrm.setLineWidth(0)
        self.statusFrm.setObjectName("statusFrm")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.statusFrm)
        self.horizontalLayout_2.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.statusLbl = QtWidgets.QLabel(self.statusFrm)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.statusLbl.setFont(font)
        self.statusLbl.setObjectName("statusLbl")
        self.horizontalLayout_2.addWidget(self.statusLbl)
        self.copyLbl = QtWidgets.QLabel(self.statusFrm)
        self.copyLbl.setMinimumSize(QtCore.QSize(150, 0))
        self.copyLbl.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.copyLbl.setFont(font)
        self.copyLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.copyLbl.setObjectName("copyLbl")
        self.horizontalLayout_2.addWidget(self.copyLbl)
        self.verticalLayout.addWidget(self.statusFrm)
        main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 451, 21))
        self.menubar.setObjectName("menubar")
        main.setMenuBar(self.menubar)

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "MainWindow"))
        self.titleLbl.setText(_translate("main", "Title"))
        self.verLbl.setText(_translate("main", "1.0.0"))
        self.dropLbl.setText(_translate("main", "Drop SRT file here"))
        self.fixCbox.setText(_translate("main", "Replace «ي» with «ی» and «ك» with «ک»"))
        self.statusLbl.setText(_translate("main", "Ready."))
        self.copyLbl.setText(_translate("main", "© LeoMoon Studios"))

import resources_rc
